---
- name: Test My Custom Module Locally
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Disable Blocking Settings
      blocking_settings:
        policy_path: policy.yaml
        violation: VIOL_ATTACK_SIGNATURE
        alarm: true
        block: true
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        