- name: VIOL_COOKIE_LENGTH
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify the allowed length of cookies
      viol_cookie_length:
        policy_path: waf_policy.yaml
        value: 4096
        format: yaml
      register: result      

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        