---
- name: Download a WAF Policy from the Git repo
  hosts: localhost
  collections:
    - skenderidis.nap
  tasks:
    - name: Clean-up. Deleting the Git folder and its contents
      file:
        path: git
        state: absent

    - name: Creating a new Git folder
      file:
        path: git
        state: directory

    - name: Clone Git repository with NAP Policies 
      git:
        repo: "{{repo}}"  # Replace with the URL of the Git repo
        dest: git  # Specify the local directory where you want to clone the repo
        version: main  # Specify the branch, tag, or commit you want to fetch

    - name: Disable signature globaly
      signatures:
        signature_id: 200001837
        enabled: False
        policy_path: app1_waf.yaml
        format: yaml
      register: result
