---
- name: Gitlab playbook
  hosts: localhost

  tasks:
    - name: Fetch policy file from GitLab
      uri:
        url: "https://gitlab.com/api/v4/projects/40361610/repository/files/policy.json/raw?ref=main"
        headers:
          PRIVATE-TOKEN: ""
        return_content: yes
      register: gitlab_file

    - name: Create Temporary File and write contents
      tempfile:
        state: file
      register: temp_file

    - name: Write GitLab File Content to Temporary File
      copy:
        content: "{{ gitlab_file.content }}"
        dest: "policy.json"

        
