---
- name: Fetch policy file and run NAP module then push to Gitlab
  hosts: localhost  # Assuming you are running Ansible locally

  tasks:

    - name: Load variables from file
      ansible.builtin.include_vars:
        file: vars.yml

    - name: Clone GitLab Repository
      shell: >
         git clone git@gitlab.com:{{ gitlab_username }}/{{ gitlab_repo_name }} {{ gitlab_repo_path }}
      args:
        warn: no
      register: git_clone_result
      ignore_errors: yes

    - name: Check if Git Clone Succeeded
      fail:
        msg: "Git clone failed with error: {{ git_clone_result.stdout }}"
      when: git_clone_result.rc != 0

    - name: Run NAP Signature update module
      signatures:
        signature_id: 123123
        policy_path: "{{ gitlab_repo_path }}/policy.json"
        #entity_type: urls
        #entity: "/test.php"
        format: json
      register: module_output

#    - name: Display Module Output
#      debug:
#       var: module_output.policy

#    - name: Save registered output to a file
#      copy:
#        content: "{{ module_output.policy }}"
#        dest: "{{ gitlab_repo_path }}/policy.json"

    - name: Commit Changes
      shell: |
        cd "{{ gitlab_repo_path }}"
        git checkout -b "{{ gitlab_new_branch }}"
        git push --set-upstream origin "{{ gitlab_new_branch }}"
        git add "{{ gitlab_policy_file }}"
        git commit -m "Signature update"
        git push origin
      args:
        warn: no
      register: git_commit_result

    - name: Check if Git Commit Succeeded
      fail:
        msg: "Git commit failed with error: {{ git_commit_result.stdout }}"
      when: git_commit_result.rc != 0
