- name: VIOL_PARAMETER_DATA_TYPE
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify Parameter's data type setting
      viol_parameter_data_type:
        policy_path: waf_policy.yaml
        parameter_name: user
        data_type: integer
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        