- name: VIOL_PARAMETER_REPEATED
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify Parameter's repeated setting
      viol_parameter_repeated:
        policy_path: waf_policy.yaml
        parameter_name: user
        enabled: false
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        