- name: VIOL_HTTP_PROTOCOL
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify HTTP Protocol Violations
      viol_http_protocol:
        policy_path: waf_policy.yaml
        http_protocol: Body in GET or HEAD requests
        enabled: False
        format: yaml        
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        