
- name: VIOL_REQUEST_LENGTH
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify Request Length
      viol_request_length:
        policy_path: waf_policy.yaml
        filetype: php
        length: 2048
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        