- name: VIOL_METHOD
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify Allowed Methods
      viol_method:
        policy_path: waf_policy.yaml
        method: DELETE
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        