- name: VIOL_URL
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Allow/Disallow a specific url
      viol_url:
        policy_path: waf_policy.yaml
        url: "index.php"
        enabled: true
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        