---
- name: Test My Custom Module Locally
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify Evasion techniques
      viol_filetype:
        policy_path: policy.yaml
        filetype: exe
        enabled: false
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        