- name: VIOL_FILETYPE
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Allow/Disallow a specific filetype
      viol_filetype:
        policy_path: waf_policy.yaml
        filetype: exe
        enabled: false
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        