
- name: VIOL_QUERY_STRING_LENGTH
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Modify Query String Length
      viol_query_string_length:
        policy_path: waf_policy.yaml
        filetype: php
        length: 2048
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        