---
- name: VIOL_HEADER_LENGTH
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Configure Header Length
      viol_header_length:
        policy_path: app1_waf.yaml
        length: 2048
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        