- name: Change enforcement mode
  hosts: localhost
  collections:
    - skenderidis.f5_awaf   
  tasks:
    - name: Change enforcement mode
      enforcement_mode:
        policy_path: policy.yaml
        enforcement: transparent
        format: yaml
      register: result

    - name: Display Module Output
      debug:
        var: result.policy

    - name: Display Module Output
      debug:
        var: result.msg        